# Site Settings
baseurl: 		""
title: 			Stuart Hadfield

name: 			stuarthadfield.github.io
description: 	A short view into who I am and what I think about things.
url: 			"http://github.com/stuarthadfield"

paginate: 		3
paginate_path: 	"blog/page:num"

twitter: 		stuartcodes
email: 			hello@stuart.com

disqus: 		stuarthadfield-github-io
analytics: 		UA-109834873-1

copyright: 		Stuart Hadfield 2017.

# Build Settings
permalinks: 	pretty
