# Site settings
title: Stuart Hadfield
email: notputtinghere@justyet.com
description: "Stuart Hadfield's github pages website."
baseurl: ""
url: "http://github.com/stuarthadfield"

# Build settings
markdown: kramdown
permalink: pretty
