# Site Settings
baseurl: 		""
title: 			Stuart Hadfield

name: 			Stuart Hadfield's <i>GitHub Pages</i> Website
description: 	A short view into who I am and what I think about things.
url: 			"http://github.com/stuarthadfield"

paginate: 		3
paginate_path: 	"blog/page:num"

twitter: 		stuartcodes
email: 			hello@stuart.come

disqus: 		your_disqus_shortname
analytics: 		UA-XXXXXXX-Y

copyright: 		2017.

# Build Settings
permalinks: 	pretty
